// swift-tools-version: 5.9
//
// The local Swift package for `prmarmot-ffi`, used for development and for the
// smoke test. It points at the XCFramework this checkout just built:
//
//     scripts/build-xcframework.sh
//     cd apple && swift build
//
// Consumers get a different package — `.github/workflows/xcframework.yml`
// writes a `Package.swift` at the repository root with a
// `.binaryTarget(url:checksum:)` pointing at the release asset. This one never
// refers to a URL, so it can never be stale.
//
// `Sources/PRMarmotCore/` is generated by the build script and gitignored.

import PackageDescription

let package = Package(
    name: "PRMarmotCore",
    platforms: [.iOS("17.2"), .macOS(.v14)],
    products: [
        .library(name: "PRMarmotCore", targets: ["PRMarmotCore"])
    ],
    targets: [
        // The module name here is the crate-derived one the generated Swift
        // imports, not a name we are free to choose. See build-xcframework.sh.
        .binaryTarget(
            name: "prmarmot_ffiFFI",
            path: "../target/xcframework/PRMarmotCore.xcframework"
        ),
        .target(
            name: "PRMarmotCore",
            dependencies: ["prmarmot_ffiFFI"],
            path: "Sources/PRMarmotCore"
        ),
        .testTarget(
            name: "SmokeTests",
            dependencies: ["PRMarmotCore"],
            path: "Tests/SmokeTests",
            resources: [.copy("Fixtures")]
        ),
    ]
)
