//! Golden parity tests: the Rust derivation must reproduce the shell
//! prototype's output byte-for-byte (as JSON values). The goldens are
//! generated by `scripts/gen-golden.sh` running the sanitized prototype jq
//! oracle (scripts/prototype-jq/) over fictional fixtures. If these fail, the port has
//! drifted from the spec — fix the port, not the golden.
//!
//! One deliberate divergence from the shell prototype is part of the spec, in
//! both the jq oracle and the port: a reviewer's standing review is their
//! latest, except that a comment does not erase an earlier approval or change
//! request (fixtures 113–116 and 206–210). The pickup age (`waitingSince`,
//! `core/src/pickup.rs`) is an extension in both as well (fixtures 101–106,
//! 117–118, 201–205, 211–212), and so is the size band (`sizeBand`,
//! `core/src/size.rs`; fixtures 101–106 and 201–203 carry change counts).

use prmarmot_core::board::{derive_rows, BoardConfig, BoardRow, IssueLinkRule, Mode};
use prmarmot_core::github::query::parse_search_response;
use serde_json::{json, Value};

const REPO: &str = "acme/widgets";
const ME: &str = "me";

fn config() -> BoardConfig {
    // The parity oracle uses a fictional tracker; runtime issue links are user config.
    BoardConfig {
        issue_link: Some(
            IssueLinkRule::new("PROJ-[0-9]+", "https://tracker.example.test/issues/{id}").unwrap(),
        ),
        ..Default::default()
    }
}

fn load(path: &str) -> Value {
    let text = std::fs::read_to_string(format!("{}/{path}", env!("CARGO_MANIFEST_DIR")))
        .unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
    serde_json::from_str(&text).unwrap()
}

/// Serialize a row exactly as the prototype's authored-mode jq does.
fn authored_json(row: &BoardRow) -> Value {
    json!({
        "number": row.number,
        "url": row.url,
        "title": row.title,
        "issue": row.issue,
        "issueUrl": row.issue_url,
        "draft": row.draft,
        "category": row.category.as_str(),
        "bug": row.bug,
        "ci": row.ci.as_str(),
        "conflict": row.conflict,
        "reviewDecision": row.review_decision,
        "reviewState": row.review_state.as_str(),
        "requested": row.requested,
        "reviews": row.reviews.iter().map(|r| json!({"login": r.login, "state": r.state})).collect::<Vec<_>>(),
        "unresolved": row.unresolved,
        "waitingSince": row.waiting_since,
        "sizeBand": row.size.map(|size| size.band().key()),
    })
}

/// Serialize a row exactly as the prototype's review-mode jq does.
fn review_json(row: &BoardRow) -> Value {
    json!({
        "number": row.number,
        "url": row.url,
        "title": row.title,
        "issue": row.issue,
        "issueUrl": row.issue_url,
        "author": row.author,
        "draft": row.draft,
        "category": row.category.as_str(),
        "bug": row.bug,
        "ci": row.ci.as_str(),
        "conflict": row.conflict,
        "myReview": row.my_review,
        "unresolved": row.unresolved,
        "createdAt": row.created_at,
        "waitingSince": row.waiting_since,
        "sizeBand": row.size.map(|size| size.band().key()),
    })
}

fn assert_rows_match(ours: Vec<Value>, golden: &Value, mode: &str) {
    let golden_rows = golden.as_array().expect("golden is an array");
    assert_eq!(
        ours.len(),
        golden_rows.len(),
        "{mode}: row count differs from prototype"
    );
    for (i, (a, b)) in ours.iter().zip(golden_rows).enumerate() {
        assert_eq!(a, b, "{mode}: row {i} differs from prototype output");
    }
}

#[test]
fn authored_mode_matches_prototype() {
    let body = load("tests/fixtures/authored_response.json");
    let (prs, rate) = parse_search_response(&body).unwrap();
    assert_eq!(prs.len(), 18);
    assert_eq!(rate.unwrap().remaining, 4987);

    let rows = derive_rows(&prs, Mode::Authored, REPO, ME, &config());
    let ours: Vec<Value> = rows.iter().map(authored_json).collect();
    assert_rows_match(ours, &load("tests/golden/authored.json"), "authored");
}

#[test]
fn review_mode_matches_prototype() {
    let body = load("tests/fixtures/review_response.json");
    let (prs, _) = parse_search_response(&body).unwrap();
    assert_eq!(prs.len(), 12);

    let rows = derive_rows(&prs, Mode::Review, REPO, ME, &config());
    let ours: Vec<Value> = rows.iter().map(review_json).collect();
    assert_rows_match(ours, &load("tests/golden/review.json"), "review");
}

#[test]
fn non_pr_nodes_are_skipped() {
    let body = json!({
        "data": {"search": {"nodes": [{}, {
            "number": 1, "title": "t", "isDraft": false, "createdAt": "2026-07-01T00:00:00Z"
        }]}}
    });
    let (prs, rate) = parse_search_response(&body).unwrap();
    assert_eq!(prs.len(), 1);
    assert!(rate.is_none());
}

#[test]
fn graphql_rate_limit_error_is_classified() {
    let body = json!({
        "data": null,
        "errors": [{"type": "RATE_LIMITED", "message": "API rate limit exceeded"}]
    });
    let err = parse_search_response(&body).unwrap_err();
    assert!(matches!(
        err,
        prmarmot_core::github::GhError::RateLimited { .. }
    ));
}

#[test]
fn graphql_partial_data_errors_are_not_silent_success() {
    let body = json!({
        "data": {"search": {"nodes": []}},
        "errors": [{"message": "field resolution failed"}]
    });
    let err = parse_search_response(&body).unwrap_err();
    assert_eq!(
        err,
        prmarmot_core::github::GhError::GraphqlErrors(vec!["field resolution failed".into()])
    );
}
