//! Golden parity tests: the Rust derivation must reproduce the shell
//! prototype's output byte-for-byte (as JSON values). The goldens are
//! generated by `scripts/gen-golden.sh` running the sanitized prototype jq
//! oracle (scripts/prototype-jq/) over fictional fixtures. If these fail, the port has
//! drifted from the spec — fix the port, not the golden.
//!
//! One deliberate divergence from the shell prototype is part of the spec, in
//! both the jq oracle and the port: a reviewer's standing review is their
//! latest, except that a comment does not erase an earlier approval or change
//! request (fixtures 113–116 and 206–210). The pickup age (`waitingSince`,
//! `core/src/pickup.rs`) is an extension in both as well (fixtures 101–106,
//! 117–118, 201–205, 211–212), and so is the size band (`sizeBand`,
//! `core/src/size.rs`; fixtures 101–106 and 201–203 carry change counts).
//!
//! One divergence is in the port only, approved by Oliver on 2026-09-25 (since
//! v0.12.1): the issue link percent-encodes the matched ID, where the jq
//! oracle substitutes it raw. The goldens cannot show it, because every
//! fixture's `PROJ-<digits>` has nothing to encode and so reads the same both
//! ways; `board::tests::a_matched_issue_id_is_percent_encoded_into_the_link`
//! pins the encoding instead. Leave the oracle raw rather than adding `@uri`.
//!
//! A second port-only divergence, approved by Oliver on 2026-09-29: the Note
//! of an approved PR follows GitHub's merge state (`mergeStateStatus`), so it
//! says "approved — waiting for CI", "checks not passing", "blocked by branch
//! rules" or "branch out of date" where the prototype always says "approved —
//! mergeable", and adds "can't rebase" when `canBeRebased` is false. The
//! fixtures carry no merge state, so the port keeps the prototype's wording for
//! them and the goldens cannot show it;
//! `board::tests::an_approved_pr_is_mergeable_only_when_github_says_so` and
//! `board::tests::a_branch_github_cannot_rebase_is_named_and_blocks_only_where_rebase_is_the_only_way`
//! pin it instead. Leave the oracle and the goldens as they are.
//!
//! A third, in what is fetched rather than how it is read (Oliver, 2026-09-29):
//! the port asks for the newest 60 reviews and newest 100 review threads
//! (`last:`), where the prototype's query asks for the oldest (`first:`).
//! GitHub returns both connections oldest first, so on a busy PR the
//! prototype's window drops the latest reviews. Every fixture has fewer, so
//! both windows hold the same nodes and the goldens cannot show it; the
//! thread `totalCount` behind "5+ unresolved comments" is pinned by
//! `board::tests::more_threads_than_the_window_make_the_count_a_lower_bound`.

use prmarmot_core::board::{derive_rows, BoardConfig, BoardRow, IssueLinkRule, Mode};
use prmarmot_core::github::query::parse_search_response;
use serde_json::{json, Value};

const REPO: &str = "acme/widgets";
const ME: &str = "me";

fn config() -> BoardConfig {
    // The parity oracle uses a fictional tracker; runtime issue links are user config.
    BoardConfig {
        issue_link: Some(
            IssueLinkRule::new("PROJ-[0-9]+", "https://tracker.example.test/issues/{id}").unwrap(),
        ),
        ..Default::default()
    }
}

fn load(path: &str) -> Value {
    let text = std::fs::read_to_string(format!("{}/{path}", env!("CARGO_MANIFEST_DIR")))
        .unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
    serde_json::from_str(&text).unwrap()
}

/// Serialize a row exactly as the prototype's authored-mode jq does.
fn authored_json(row: &BoardRow) -> Value {
    json!({
        "number": row.number,
        "url": row.url,
        "title": row.title,
        "issue": row.issue,
        "issueUrl": row.issue_url,
        "draft": row.draft,
        "category": row.category.as_str(),
        "bug": row.bug,
        "ci": row.ci.as_str(),
        "conflict": row.conflict,
        "reviewDecision": row.review_decision,
        "reviewState": row.review_state.as_str(),
        "requested": row.requested,
        "reviews": row.reviews.iter().map(|r| json!({"login": r.login, "state": r.state})).collect::<Vec<_>>(),
        "unresolved": row.unresolved,
        "waitingSince": row.waiting_since,
        "sizeBand": row.size.map(|size| size.band().key()),
    })
}

/// Serialize a row exactly as the prototype's review-mode jq does.
fn review_json(row: &BoardRow) -> Value {
    json!({
        "number": row.number,
        "url": row.url,
        "title": row.title,
        "issue": row.issue,
        "issueUrl": row.issue_url,
        "author": row.author,
        "draft": row.draft,
        "category": row.category.as_str(),
        "bug": row.bug,
        "ci": row.ci.as_str(),
        "conflict": row.conflict,
        "myReview": row.my_review,
        "unresolved": row.unresolved,
        "createdAt": row.created_at,
        "waitingSince": row.waiting_since,
        "sizeBand": row.size.map(|size| size.band().key()),
    })
}

fn assert_rows_match(ours: Vec<Value>, golden: &Value, mode: &str) {
    let golden_rows = golden.as_array().expect("golden is an array");
    assert_eq!(
        ours.len(),
        golden_rows.len(),
        "{mode}: row count differs from prototype"
    );
    for (i, (a, b)) in ours.iter().zip(golden_rows).enumerate() {
        assert_eq!(a, b, "{mode}: row {i} differs from prototype output");
    }
}

#[test]
fn authored_mode_matches_prototype() {
    let body = load("tests/fixtures/authored_response.json");
    let (prs, rate) = parse_search_response(&body).unwrap();
    assert_eq!(prs.len(), 18);
    assert_eq!(rate.unwrap().remaining, 4987);

    let rows = derive_rows(&prs, Mode::Authored, REPO, ME, &config());
    let ours: Vec<Value> = rows.iter().map(authored_json).collect();
    assert_rows_match(ours, &load("tests/golden/authored.json"), "authored");
}

#[test]
fn review_mode_matches_prototype() {
    let body = load("tests/fixtures/review_response.json");
    let (prs, _) = parse_search_response(&body).unwrap();
    assert_eq!(prs.len(), 12);

    let rows = derive_rows(&prs, Mode::Review, REPO, ME, &config());
    let ours: Vec<Value> = rows.iter().map(review_json).collect();
    assert_rows_match(ours, &load("tests/golden/review.json"), "review");
}

#[test]
fn non_pr_nodes_are_skipped() {
    let body = json!({
        "data": {"search": {"nodes": [{}, {
            "number": 1, "title": "t", "isDraft": false, "createdAt": "2026-07-01T00:00:00Z"
        }]}}
    });
    let (prs, rate) = parse_search_response(&body).unwrap();
    assert_eq!(prs.len(), 1);
    assert!(rate.is_none());
}

#[test]
fn graphql_rate_limit_error_is_classified() {
    let body = json!({
        "data": null,
        "errors": [{"type": "RATE_LIMITED", "message": "API rate limit exceeded"}]
    });
    let err = parse_search_response(&body).unwrap_err();
    assert!(matches!(
        err,
        prmarmot_core::github::GhError::RateLimited { .. }
    ));
}

#[test]
fn graphql_partial_data_errors_are_not_silent_success() {
    let body = json!({
        "data": {"search": {"nodes": []}},
        "errors": [{"message": "field resolution failed"}]
    });
    let err = parse_search_response(&body).unwrap_err();
    assert_eq!(
        err,
        prmarmot_core::github::GhError::GraphqlErrors(vec!["field resolution failed".into()])
    );
}
